### ISSUE TITLE
ERROR Class 'App\Exceptions\Handler' not found

### ISSUE THREAD

**Issue by minkbear** [dmitry-ivanov/laravel-console-logger#1]
Thanks for yours effort.

I found the error below

> PHP Fatal error:  Class 'App\Exceptions\Handler' not found in C:\testprojecct\vendor\illuminated\console-
> logger\src\ExceptionHandler.php on line 8
> PHP Fatal error:  Uncaught ReflectionException: Class Illuminated\Console\Except
> ionHandler does not exist in C:testprojecct\vendor\laravel\framework\src\Illuminate\Container\Container.

My app name is Test so the correct namespace is 'Test\Exceptions\Handler'.

Please advice.

**Comment by dmitry-ivanov** [comment]
Hi, @minkbear !

Thanks for posting, an issue was fixed in `1.0.8` release. Please, update and try again.

Thanks and have a great day!

**Comment by minkbear** [comment]
@dmitry-ivanov work perfect. Thank you.
