### ISSUE TITLE
Sentry doesn't send  events from Loggable

### ISSUE THREAD

**Issue by itelmenko** [dmitry-ivanov/laravel-console-logger#10]
### Versions:

- Package Version: 6.0.0
- PHP Version: 7.2.24

### Description:

When I use Loggable I don't send events to https://sentry.io on Exception. 
...

### Steps to reproduce:

1. Create console command. Add `use Loggable` in it.
2. Install Sentry: Create project in sentry.io, install sentry package, define SENTRY_LARAVEL_DSN and etc.
3. try to throw new Exception. You will not see this event in Sentry's dashboard
4. Remove `use Loggable` and try to throw new Exception. You will see this event

**Comment by dmitry-ivanov** [comment]
Yeah, that's a known issue.

Both of the packages are overwriting standard "ExceptionHandler", I believe. And basically are doing the same thing. Feel free to open PR, if you want to help with that 👍

**Comment by itelmenko** [comment]
Please, pay attention to this PR https://github.com/dmitry-ivanov/laravel-console-logger/pull/11
What do you think about changes?

**Comment by dmitry-ivanov** [comment]
Sentry support added in [6.1.0](https://github.com/dmitry-ivanov/laravel-console-logger/releases/tag/6.1.0).
