### ISSUE TITLE
Can't install on 5.6

### ISSUE THREAD

**Issue by dansleboby** [dmitry-ivanov/laravel-console-logger#13]
### Versions:

- Package Version: 5.6.*
- PHP Version: 7.3.14

php ../composer.phar require "illuminated/console-logger:5.6.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install illuminated/console-logger 5.6.3
    - Conclusion: don't install illuminated/console-logger 5.6.2
    - Conclusion: don't install illuminated/console-logger 5.6.1
    - Conclusion: don't install illuminated/console-logger 5.6.0
    - Conclusion: remove symfony/filesystem v5.0.8
    - Installation request for illuminated/console-logger 5.6.* -> satisfiable by illuminated/console-logger[5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.x-dev].
    - Conclusion: don't install symfony/filesystem v5.0.8
    - illuminated/console-logger 5.6.x-dev requires illuminated/helper-functions 5.6.* -> satisfiable by illuminated/helper-functions[5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.x-dev].
    - illuminated/helper-functions 5.6.0 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.1 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.2 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.3 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.4 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.5 requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10,
v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.
0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9,
 v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - illuminated/helper-functions 5.6.x-dev requires symfony/filesystem ^4.0 -> satisfiable by symfony/filesystem[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.
10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v
4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.
3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8].
    - Can only install one of: symfony/filesystem[4.0.x-dev, v5.0.8].
    - Can only install one of: symfony/filesystem[4.1.x-dev, v5.0.8].
    - Can only install one of: symfony/filesystem[4.2.x-dev, v5.0.8].
    - Can only install one of: symfony/filesystem[4.3.x-dev, v5.0.8].
    - Can only install one of: symfony/filesystem[4.4.x-dev, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-BETA1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-BETA2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-BETA3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-BETA4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-RC1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.0-RC2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.10, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.11, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.12, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.13, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.14, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.15, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.5, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.6, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.7, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.8, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.0.9, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.0, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.0-BETA1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.0-BETA2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.0-BETA3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.10, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.11, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.12, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.5, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.6, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.7, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.8, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.1.9, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.0, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.0-BETA1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.0-BETA2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.0-RC1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.10, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.11, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.12, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.5, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.6, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.7, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.8, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.2.9, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.0, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.0-BETA1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.0-BETA2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.0-RC1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.10, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.11, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.5, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.6, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.7, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.8, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.3.9, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.0, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.0-BETA1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.0-BETA2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.0-RC1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.1, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.2, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.3, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.4, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.5, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.6, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.7, v5.0.8].
    - Can only install one of: symfony/filesystem[v4.4.8, v5.0.8].
    - Installation request for symfony/filesystem (locked at v5.0.8) -> satisfiable by symfony/filesystem[v5.0.8].

Installation failed, reverting ./composer.json to its original content.

**Comment by dmitry-ivanov** [comment]
Please, check your `composer.json`.

Here's [the Laravel's `composer.json` on 5.6](https://github.com/laravel/framework/blob/5.6/composer.json), and here's the [package's `composer.json` on 5.6](https://github.com/dmitry-ivanov/laravel-console-logger/blob/5.6/composer.json). Both of them are using Symfony packages of `^4.0`.

It seems that in your `composer.json` you're trying to use `symfony/filesystem` higher than 5:
> `symfony/filesystem` (locked at v5.0.8)
