### ISSUE TITLE
Support for Laravel 10

### ISSUE THREAD

**Issue by dansleboby** [dmitry-ivanov/laravel-console-logger#15]
Hello,

Firstly, I wanted to express how much I appreciate your package. It has been incredibly useful for my projects. The functionality and ease of use it offers have saved me a lot of time and effort.

Sadly, due to my current commitments, I'm unable to create a PR at the moment. However, I noticed that the package could benefit from support for Laravel 10. 

I was hoping you might consider adding this support in a future update. It would be immensely beneficial for the community, and I'm sure many others would appreciate it as much as I would.

Thank you for your hard work and dedication to this package. I look forward to seeing its continued growth and evolution.

Warm regards

**Comment by dmitry-ivanov** [comment]
@dansleboby Hey,

Thank you so much for your kind words!

I remember about this, and my other packages and will definitely update them when I have time for that. Unfortunately, I have to focus on other things now. Sorry for the delay and inconvenience.

Also, I plan to add donation goals on BMC or Patreon to make maintaining of my packages faster and more reliable. That way, people who find my packages useful could support me and help me dedicate the required time to them.

Kind regards,
Dmitry

**Comment by dmitry-ivanov** [comment]
@dansleboby I've just [released 10.0.0](https://github.com/dmitry-ivanov/laravel-console-logger/releases/tag/10.0.0) 🎉

Please, consider [supporting further development](https://buymeacoffee.com/dmitry.ivanov).

Thanks!
