### ISSUE TITLE
Can you come up with a version that supports Laravel 11? 

### ISSUE THREAD

**Issue by wwx101123** [dmitry-ivanov/laravel-console-logger#16]
Can you come up with a version that supports Laravel 11? The current PHP version is 8.3, which seems unsupported~!

**Comment by wwx101123** [comment]
Your plugin is fantastic 🎉， Hope to receive your support!

**Comment by dmitry-ivanov** [comment]
Thanks! Yeah, I remember about the Laravel 11 upgrade, and will do it when I have time for that.
