### ISSUE TITLE
Compatibility issue with Laravel's class optimizer

### ISSUE THREAD

**Issue by maclof** [dmitry-ivanov/laravel-console-logger#3]
Hey,

Is there a reason we need this line in composer.json?
https://github.com/dmitry-ivanov/laravel-console-logger/blob/master/composer.json#L30

I'm using this in a Laravel 5.2 project and if I use the `php artisan optimize` command I get the following error:
PHP Fatal error:  Cannot declare class Symfony\Component\Finder\Glob, because the name is already in use in /code/bootstrap/cache/compiled.php on line 17279

However if I remove that line from composer.json and rerun the optimize command everything works as expected.

**Comment by dmitry-ivanov** [comment]
Hey,

Can't reproduce that problem on the clean Laravel 5.2 project.

```
➜  laravel-52 composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
```

Can you provide some more details?
Maybe github repo url?

**Comment by maclof** [comment]
Hey @dmitry-ivanov 

I just tested in fresh Laravel 5.2 project and the issue is definately there, but the way to trigger this is to make sure that in the .env file, you're setting APP_ENV to production and APP_DEBUG to false, e.g.

```
APP_ENV=production
APP_DEBUG=false
```

Then the issue will appear:

```
C:\xampp\htdocs\52test
λ php artisan optimize
Generating optimized class loader
Compiling common classes

C:\xampp\htdocs\52test
λ php artisan
PHP Fatal error:  Cannot declare class Symfony\Component\Finder\SplFileInfo, because the name is already in use in C:\xampp\htdocs\52test\bootstrap\cache\compiled.php on line 16715

Fatal error: Cannot declare class Symfony\Component\Finder\SplFileInfo, because the name is already in use in C:\xampp\htdocs\52test\bootstrap\cache\compiled.php on line 16715
```

**Comment by dmitry-ivanov** [comment]
@maclof Yep, now I can see it.

You got that problem, because you're missing "clear-compiled" step, before optimize.
https://github.com/laravel/framework/issues/9678

Check your `composer.json` file for new Laravel 5.2 project:
```
"post-update-cmd": [
    "Illuminate\\Foundation\\ComposerScripts::postUpdate",
    "php artisan optimize"
]
```

>"Illuminate\\Foundation\\ComposerScripts::postUpdate",
That is where `static::clearCompiled();` called automatically for you.

So, if you try to run:
```
➜  laravel-52 composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postUpdate
> php artisan optimize
Generating optimized class loader
Compiling common classes
```

It still works perfectly.

**Comment by maclof** [comment]
@dmitry-ivanov you're completely right, that's very odd

Thanks for looking at it for me so quickly!
