### ISSUE TITLE
Question regarding reservedMemory var

### ISSUE THREAD

**Issue by JayBizzle** [dmitry-ivanov/laravel-console-logger#4]
Hi,

Thanks for this great package. I was just looking through the code and wondered if you could explain what the following line is for.
https://github.com/dmitry-ivanov/laravel-console-logger/blob/829418a765792cdc77ebd67bc7cc07f713fee219/src/Exceptions/ExceptionHandler.php#L49

Thanks

**Comment by dmitry-ivanov** [comment]
Hi, @JayBizzle !

Thanks for your kind words! :)

I'm reserving a bit of memory (while registering shutdown function), to have an ability to execute all required operations while handling "Fatal Error: Allowed Memory Size of ... Bytes Exhausted".

If you take a look on handling method:
https://github.com/dmitry-ivanov/laravel-console-logger/blob/7ae85f6dc03d6abe7d9c7538e908027df84a1c8f/src/Exceptions/ExceptionHandler.php#L54-L71

You'll see, that the first thing I do - is releasing that memory:
>$this->reservedMemory = null;

And after that, I'm able to do all stuff, which you can see there below (which requires a bit of memory too).

PS: I've saw that trick at Monolog actually, so hat tips to Monolog :)
https://github.com/Seldaek/monolog/blob/master/src/Monolog/ErrorHandler.php

**Comment by JayBizzle** [comment]
Thanks for taking the time to explain :+1:
