### ISSUE TITLE
Exception handler conflicts with existing exception handler

### ISSUE THREAD

**Issue by arondeparon** [dmitry-ivanov/laravel-console-logger#5]
When creating a command implementation using the `LoggableTrait`, the exception handler is overwritten by default. 

This can cause trouble with using external exception handlers (such as Sentry), because it will prevent errors from being reported .

**Comment by dmitry-ivanov** [comment]
Makes sense. Both are overwriting standard `ExceptionHandler` for the same purposes.
Basically they are doing the same thing. `Console-logger` is just designed specifically for your console commands, providing some additional features for them.

You can setup notifications for your `Loggable` commands, so they would be covered by `console-logger`, and you don't need Sentry (or another handler) for them.

**Comment by dmitry-ivanov** [comment]
Sentry support added in [6.1.0](https://github.com/dmitry-ivanov/laravel-console-logger/releases/tag/6.1.0).
