### ISSUE TITLE
5.6 incompatible with monolog > 1.23

### ISSUE THREAD

**Issue by aronduby** [dmitry-ivanov/laravel-console-logger#9]
### Versions:

- Package Version: 5.6.*

### Description:

Monologer changed the signature of Monolog\Formatter\NormalizerFormatter::normalize in 1.24 which is incompatable (like first portion of #6 ) installing specifically to 1.23 makes it work again.

**Comment by dmitry-ivanov** [comment]
Released [5.6.3](https://github.com/dmitry-ivanov/laravel-console-logger/releases/tag/5.6.3) 👍
